name: picasa-snap
title: Picasa
version: "3.9.141.259"
summary: "Picasa is free photo management software from Google."
description: |
    Picasa is free photo management software from Google that helps you find, edit and share your photos in
    seconds.

    Picasa has file importing and tracking features, as well as tags, facial recognition, and collections for further sorting. It also offers several basic photo editing functions, including color enhancement, red eye reduction, and cropping. Keywords attached to JPEG files in Picasa can be read by other image library software like Adobe Photoshop Album, Adobe Bridge, Adobe Photoshop Lightroom, digiKam, Aperture, and iPhoto.

    *Note: This Windows application runs on Linux using the Wine compatibility layer. This software was discontinued in 2016. However, most features still work on modern systems.*

    - Installation: During the first run, wine will be configured and the actuall installer will be downloaded and installed, this can take several minutes and it's expected. If a "Wine configuration" windows pops up, click "Ok" to proceed with the installation.

    - Things that do NOT work:
        - *Places* panel
        - Logging in into your Google account
        - Export to web albums

    - Things that work:
        - Everything else

icon: snap/gui/picasa.png

grade: stable

base: core18
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="    # Prevent pop-ups about Wine Mono and Wine Gecko
  SOMMELIER_STRICT: "1"                                    # Make Sommelier exit when unset variable is used. (useful to find bugs in sommelier)

apps:
  picasa-snap:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/Program Files (x86)/Google/Picasa3/Picasa3.exe"
      INSTALL_URL: "https://archive.org/download/picasa-3.9.141.259/picasa39-setup.exe"
      INSTALL_FLAGS: "/S /L"
      TRICKS: "ie8"
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
 # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  installer:
    plugin: dump
    source: installer

  # The sommelier script helps you snap Windows applications using Wine. It 
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git

# These plugs are used to connect the snap to the wine runtime.
plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable
